source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

project 'CPEExperienceExample'
workspace 'CPEExperienceExampleWorkspace'

target 'CPEExperienceExample' do
    
    use_frameworks!
    
    pod 'CPEData',          :path => '../../cpe-manifest-ios-data'
    pod 'CPEExperience',    :path => '../'

end