source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

project 'NextGenExample'
workspace 'NextGenExampleWorkspace'

target 'NextGenExample' do
    
    use_frameworks!
    
    ################################
    ## Required NextGen libraries ##
    ################################
    # Base Data
    pod 'NextGenDataManager',       :path => '../../cpe-manifest-ios-data'
    
    # Playback
    pod 'google-cast-sdk',          '~> 3.3'
    
    # UI
    pod 'GoogleMaps'
    pod 'SDWebImage',               '~> 4.0'
    pod 'UAProgressView'
    pod 'MBProgressHUD',            '~> 0.9.2'
    
    # Helpers
    pod 'ReachabilitySwift'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
